// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package springapp.domain;

import org.springframework.beans.factory.annotation.Configurable;
import springapp.domain.OrderItem;

privileged aspect OrderItem_Roo_Configurable {
    
    declare @type: OrderItem: @Configurable;
    
}
