// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package springapp.domain;

import org.springframework.beans.factory.annotation.Configurable;
import springapp.domain.ProductOrderIntegrationTest;

privileged aspect ProductOrderIntegrationTest_Roo_Configurable {
    
    declare @type: ProductOrderIntegrationTest: @Configurable;
    
}
