// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package springapp.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import springapp.domain.ProductOrder;
import springapp.domain.ProductOrderDataOnDemand;

privileged aspect ProductOrderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ProductOrderDataOnDemand: @Component;
    
    private Random ProductOrderDataOnDemand.rnd = new SecureRandom();
    
    private List<ProductOrder> ProductOrderDataOnDemand.data;
    
    public ProductOrder ProductOrderDataOnDemand.getNewTransientProductOrder(int index) {
        ProductOrder obj = new ProductOrder();
        setDeliveryDate(obj, index);
        setOrderDate(obj, index);
        return obj;
    }
    
    public void ProductOrderDataOnDemand.setDeliveryDate(ProductOrder obj, int index) {
        Date deliveryDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setDeliveryDate(deliveryDate);
    }
    
    public void ProductOrderDataOnDemand.setOrderDate(ProductOrder obj, int index) {
        Date orderDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setOrderDate(orderDate);
    }
    
    public ProductOrder ProductOrderDataOnDemand.getSpecificProductOrder(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ProductOrder obj = data.get(index);
        Long id = obj.getId();
        return ProductOrder.findProductOrder(id);
    }
    
    public ProductOrder ProductOrderDataOnDemand.getRandomProductOrder() {
        init();
        ProductOrder obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return ProductOrder.findProductOrder(id);
    }
    
    public boolean ProductOrderDataOnDemand.modifyProductOrder(ProductOrder obj) {
        return false;
    }
    
    public void ProductOrderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = ProductOrder.findProductOrderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ProductOrder' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ProductOrder>();
        for (int i = 0; i < 10; i++) {
            ProductOrder obj = getNewTransientProductOrder(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
