// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package springapp.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;
import springapp.domain.ProductOrder;
import springapp.domain.ProductOrderDataOnDemand;
import springapp.domain.ProductOrderIntegrationTest;

privileged aspect ProductOrderIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ProductOrderIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ProductOrderIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ProductOrderIntegrationTest: @Transactional;
    
    @Autowired
    private ProductOrderDataOnDemand ProductOrderIntegrationTest.dod;
    
    @Test
    public void ProductOrderIntegrationTest.testCountProductOrders() {
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", dod.getRandomProductOrder());
        long count = ProductOrder.countProductOrders();
        Assert.assertTrue("Counter for 'ProductOrder' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ProductOrderIntegrationTest.testFindProductOrder() {
        ProductOrder obj = dod.getRandomProductOrder();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to provide an identifier", id);
        obj = ProductOrder.findProductOrder(id);
        Assert.assertNotNull("Find method for 'ProductOrder' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ProductOrder' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ProductOrderIntegrationTest.testFindAllProductOrders() {
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", dod.getRandomProductOrder());
        long count = ProductOrder.countProductOrders();
        Assert.assertTrue("Too expensive to perform a find all test for 'ProductOrder', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ProductOrder> result = ProductOrder.findAllProductOrders();
        Assert.assertNotNull("Find all method for 'ProductOrder' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ProductOrder' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ProductOrderIntegrationTest.testFindProductOrderEntries() {
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", dod.getRandomProductOrder());
        long count = ProductOrder.countProductOrders();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ProductOrder> result = ProductOrder.findProductOrderEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ProductOrder' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ProductOrder' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ProductOrderIntegrationTest.testFlush() {
        ProductOrder obj = dod.getRandomProductOrder();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to provide an identifier", id);
        obj = ProductOrder.findProductOrder(id);
        Assert.assertNotNull("Find method for 'ProductOrder' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProductOrder(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'ProductOrder' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductOrderIntegrationTest.testMergeUpdate() {
        ProductOrder obj = dod.getRandomProductOrder();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to provide an identifier", id);
        obj = ProductOrder.findProductOrder(id);
        boolean modified =  dod.modifyProductOrder(obj);
        Integer currentVersion = obj.getVersion();
        ProductOrder merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ProductOrder' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ProductOrderIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", dod.getRandomProductOrder());
        ProductOrder obj = dod.getNewTransientProductOrder(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ProductOrder' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'ProductOrder' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ProductOrderIntegrationTest.testRemove() {
        ProductOrder obj = dod.getRandomProductOrder();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ProductOrder' failed to provide an identifier", id);
        obj = ProductOrder.findProductOrder(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'ProductOrder' with identifier '" + id + "'", ProductOrder.findProductOrder(id));
    }
    
}
